collections:
  - containers.podman
  
galaxy_info:
  role_name: containerhost_podman
  author: jamesread
  description: Sets up a host to run podman.
  license: GPL-3.0-or-later
  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions: 
        - 7
        - 8 
    - name: Fedora
      versions: 
        - all
  galaxy_tags:
    - podman

