galaxy_info:
  role_name: systemd_kvm_hypervisor
  author: jamesread
  description: Installs KVM, libvirt, etc.
  license: GPL-3.0-or-later
  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions: 
        - 7
        - 8 
    - name: Fedora
      versions: 
        - all

