namespace: "jamesread"
name: "soe"
version: "4.0.0"
readme: "README.md"
authors:
  - "James Read <contact@jread.com>"
dependencies: 
license: 
  - "GPL-3.0-or-later"
tags: 
  - jwr
  - podman
repository: "https://github.com/jamesread/jwr-soe-ansible"
documentation: "https://github.com/jamesread/jwr-soe-ansible"
homepage: "https://github.com/jamesread/jwr-soe-ansible"
issues: "https://github.com/jamesread/jwr-soe-ansible/issues"
