#!/usr/bin/env ansible-playbook 

- hosts: [group_cifs]
  roles: [cifs]

- hosts: [group_common]
  roles: [common]

- hosts: [group_containerhost_podman]
  roles: [containerhost_podman]

- hosts: [group_machine_kiosk]
  roles: [machine_kiosk]

- hosts: [group_machine_workstation]
  roles: [machine_workstation]

- hosts: [group_podman_grafana]
  roles: [podman_grafana]

- hosts: [group_podman_openhab]
  roles: [podman_openhab]

- hosts: [group_podman_prometheus]
  roles: [podman_prometheus]

- hosts: [group_systemd_condor_compute]
  roles: [systemd_condor_compute]

- hosts: [group_systemd_jenkins]
  roles: [systemd_jenkins]

- hosts: [group_systemd_kvm_hypervisor]
  roles: [systemd_kvm_hypervisor]

- hosts: [group_systemd_webserver]
  roles: [systemd_webserver]

