- name: package - podman
  package:
    name: podman
    state: present

- name: service - podman
  service:
    name: podman
    state: started
    enabled: yes

- name: haproxy
  block:
    - name: package - haproxy
      package:
        name: haproxy
        state: present

    - name: template - haproxy
      tags: haproxy
      template:
        src: "{{ cfg_haproxy }}"
        dest: /etc/haproxy/haproxy.cfg
        mode: 0644
      notify:
        - service haproxy restart

    - name: service - haproxy
      tags: haproxy
      service: 
        name: haproxy
        state: started
        enabled: yes
  when: cfg_haproxy is defined
