- name: package - haproxy
  package:
    name: haproxy
    state: present

- name: template - haproxy
  tags: haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify:
    - service haproxy restart

- name: service - haproxy
  tags: haproxy
  service: 
    name: haproxy
    state: started
    enabled: yes
