- name: Restart ssh
  service:
    name: sshd
    state: restarted
  when: ansible_distribution != 'Debian'

- name: Restart ssh
  service:
    name: ssh
    state: restarted
  when: ansible_distribution == 'Debian'
