---
- include: family_rh.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'

- include: family_deb.yml
  when: ansible_distribution == 'Debian'

# Start NTP
#- service: name={{ item }} state=started enabled=yes
#  name: start essential services
#  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'
#  with_items: 
#    - ntpd

- name: package - node-exporter
  package:
    name: node_exporter
    state: latest

- name: service - node-exporter
  service: 
    name: node_exporter
    state: started
    enabled: yes

- name: Update the /etc/ssh/sshd_config file
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^UseDNS"
    line: "UseDNS no"
    insertafter: EOF
    state: present
  notify: Restart ssh


